### ISSUE TITLE
Add a link to the extension in GitHub & Fix image display in vscode marketplace

### ISSUE THREAD

**Issue by alexanderadam** [sevenc-nanashi/gemfile-lock-highlight#1]
It would be great if you could add a link [to the extension](https://marketplace.visualstudio.com/items?itemName=sevenc-nanashi.gemfile-lock-highlight) in GitHub and maybe even fix the displayed image in the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=sevenc-nanashi.gemfile-lock-highlight).

Besides from that your extension is working perfect. Thank you so much for it! :raised_hands: 

**PS:** Is there any way to associate the syntax highlighting automatically? Does it need another language definition? I shouldn't go for assigning the `.lock` extension since bundler isn't the only thing that's using files with the `lock` extension. :thinking:

**Comment by sevenc-nanashi** [comment]
Done!
To PS:
I think vscode will associate `Gemfile.lock` to this extension. If you need this highlight for other extension, you can set `"your-file-name-here": "gemfile-lock"` to `files.associations` in settings.json.
